//
//  SignInUpInteractor.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 10/30/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignInUpBusinessLogic {
    func doSomething(request: SignInUp.Something.Request)
}

protocol SignInUpDataStore {
    //var name: String { get set }
}

class SignInUpInteractor: SignInUpBusinessLogic, SignInUpDataStore {
    
    var presenter: SignInUpPresentationLogic?
    var worker: SignInUpWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: SignInUp.Something.Request) {
        worker = SignInUpWorker()
        worker?.doSomeWork()
        
        let response = SignInUp.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
