//
//  SignInUpModels.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 10/30/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SignInUpModels {
    
    // MARK: Use cases
    
    enum SetSignInUpButtonTitle {
        struct Request {
        }
        
        struct Response {
            var isSignInClicked: Bool
        }
        
        struct ViewModel {
            var title: String
        }
    }
    
    enum SignInUp {
        struct Request {
            var login: String?
            var password:String?
        }
        
        struct Response {
            var signInUpResult: SignInUpResult
        }
        
        struct ViewModel {
            var errorTitle: String
            var errorMessage: String
        }
    }
    
}
