//
//  SignInUpPresenter.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 10/30/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignInUpPresentationLogic {
    func presentSomething(response: SignInUp.Something.Response)
}

class SignInUpPresenter: SignInUpPresentationLogic {
    
    weak var viewController: SignInUpDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: SignInUp.Something.Response) {
        let viewModel = SignInUp.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
