//
//  SignInUpInteractor.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 10/30/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignInUpBusinessLogic {
    func setUpButonTitle()
    func signInUp(request: SignInUpModels.SignInUp.Request)
}

protocol SignInUpDataStore {
    var isSignInClicked: Bool! { get set }
}

class SignInUpInteractor: SignInUpBusinessLogic, SignInUpDataStore {
    
    var presenter: SignInUpPresentationLogic?
    var worker: SignInUpWorker?
    var isSignInClicked: Bool!
    
    // MARK: Set button title
    
    func setUpButonTitle() {
        let response = SignInUpModels.SetSignInUpButtonTitle.Response(isSignInClicked: isSignInClicked)
        presenter?.presentButtonTitle(response: response)
    }
    
    // MARK: SignInUp
    
    func signInUp(request: SignInUpModels.SignInUp.Request) {
        worker = SignInUpWorker()
        if isSignInClicked {
            worker?.signIn(login: request.login, password: request.password, handler: { [weak self] (result) in
                let response = SignInUpModels.SignInUp.Response(signInUpResult: result)
                self?.presenter?.presentSignInUpResult(response: response)
            })
        } else {
            worker?.signUp(login: request.login, password: request.password, handler: { [weak self] (result) in
                let response = SignInUpModels.SignInUp.Response(signInUpResult: result)
                self?.presenter?.presentSignInUpResult(response: response)
            })
        }
    }
}
