//
//  SignInUpPresenter.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 10/30/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignInUpPresentationLogic {
    func presentButtonTitle(response: SignInUpModels.SetSignInUpButtonTitle.Response)
    func presentSignInUpResult(response: SignInUpModels.SignInUp.Response)
}

class SignInUpPresenter: SignInUpPresentationLogic {
    
    weak var viewController: SignInUpDisplayLogic?
    
    // MARK: Present button title
    
    func presentButtonTitle(response: SignInUpModels.SetSignInUpButtonTitle.Response) {
        let buttonTitle = response.isSignInClicked ? "Войти" : "Зарегистрироваться"
        let viewModel = SignInUpModels.SetSignInUpButtonTitle.ViewModel(title: buttonTitle)
        viewController?.displaySignInUpButtonTitle(viewModel: viewModel)
    }
    
    // MARK: Present SignIn SignUp result
    
    func presentSignInUpResult(response: SignInUpModels.SignInUp.Response) {
        if case let SignInUpResult.failure(error: error) = response.signInUpResult {
            let viewModel = SignInUpModels.SignInUp.ViewModel(errorTitle: error.title, errorMessage: error.description)
            if error.code == .errorWithAction {
                viewController?.signInUpFailureWithAction(viewModel: viewModel)
            } else {
                viewController?.signInUpFailureWithNoAction(viewModel: viewModel)
            }
        } else {
            let viewModel = SignInUpModels.SignInUp.ViewModel(errorTitle: "", errorMessage: "")
            viewController?.signInUpSuccessful(viewModel: viewModel)
        }
    }
}
