//
//  FavouriteWorker.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 11/4/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import RealmSwift

class FavouriteDBWorker {
   
    func getFavouriteMovies() -> Results<DetailMovie> {
        return RealmMovieManager.getMovies(status: .favourite)
    }
    
}
