//
//  FavouriteInteractor.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 11/4/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import RealmSwift


protocol FavouriteBusinessLogic {
    func getMovies(request: FavouriteModels.GetMovies.Request)
    func selectMovie(request: FavouriteModels.SelectMovie.Request)
    func removeMovie(request: FavouriteModels.RemoveMovie.Request)
}

protocol FavouriteDataStore {
    var movies: Results<DetailMovie>! { get }
    var selectedMovieId: Int! { get }
}

class FavouriteInteractor: FavouriteBusinessLogic, FavouriteDataStore {
    
    var presenter: FavouritePresentationLogic?
    var worker: FavouriteDBWorker?
    var dataBaseWorker: DetailMovieDBWorker?
   
    var selectedMovieId: Int!
    var movies: Results<DetailMovie>!
    
    // MARK: Get movies
    
    func getMovies(request: FavouriteModels.GetMovies.Request) {
        worker = FavouriteDBWorker()
        
        movies = worker?.getFavouriteMovies()
        
        let response = FavouriteModels.GetMovies.Response(movies: movies)
        presenter?.presentMovies(response: response)
    }
    
    // MARK: Select movie
    
    func selectMovie(request: FavouriteModels.SelectMovie.Request) {
        selectedMovieId = request.movieId
    }
    
    //MARK: - Remove movie from list
    
    func removeMovie(request: FavouriteModels.RemoveMovie.Request) {
        dataBaseWorker = DetailMovieDBWorker()
        if let movieId = request.removedMovie.movieId {
            dataBaseWorker?.change(status: .favourite, for: movieId)
            
            let response = FavouriteModels.GetMovies.Response(movies: movies)
            presenter?.presentMovies(response: response)
        }
    }
}
