//
//  FavouriteInteractor.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 11/4/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavouriteBusinessLogic {
    func getMovies(request: FavouriteModels.GetMovies.Request)
}

protocol FavouriteDataStore {
    var movies: [DetailMovie]! { get }
}

class FavouriteInteractor: FavouriteBusinessLogic, FavouriteDataStore {
    
    var presenter: FavouritePresentationLogic?
    var worker: FavouriteWorker?
   
    var movies: [DetailMovie]!
    
    // MARK: Get movies
    
    func getMovies(request: FavouriteModels.GetMovies.Request) {
//        worker = FavouriteWorker()
//        worker?.doSomeWork()
        
        movies = ListManager.listManager.getMovies(from: .favouriteList)
        
        let response = FavouriteModels.GetMovies.Response(movies: movies)
        presenter?.presentMovies(response: response)
    }
}
