//
//  DetailMovieWorker.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 10/13/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailMovieWorker {
    
    
    func getMovieDetailInfo(withMovieId movieId: Int, completionHandler: @escaping (DetailMovie?) -> Void) {
        APIMovieManager.fetchDetailMovie(movieId: movieId) { (detailMovie, result) in
            switch result {
            case .Success:
                guard let detailMovie = detailMovie else { return }
                completionHandler(detailMovie)
//                DispatchQueue.main.async {
//                    self.configureUI()
//                }
            case .Failure:
                print("Error")
                completionHandler(nil)
//                let alert = UIHelpers.showAlert(withTitle: "Ошибка",
//                                                message: "Данные не были получены из сети",
//                                                buttonTitle: "Вернуться назад",
//                                                handler: { action in
//                                                    self.navigationController?.popViewController(animated: true)
//                })
                
//                self.present(alert, animated: true, completion: nil)
                
            }
        }
    }
}
