//
//  DetailMovieViewController.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 10/13/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import WebKit

protocol DetailMovieDisplayLogic: class {
    func displayMovieDetails(viewModel: DetailMovieModels.ShowDetails.ViewModel)
    func updateUIForFavouriteStatus(viewModel: DetailMovieModels.SetFavouriteStatus.ViewModel)
    func updateUIForWatchLaterStatus(viewModel: DetailMovieModels.SetWatchLaterStatus.ViewModel)
    func updateOverviewReviews(viewModel: DetailMovieModels.SelectOverviewReviewsSegmentedControl.ViewModel)
}

class DetailMovieViewController: UIViewController {
    
    @IBOutlet var trailerPlayer: WKWebView!
    @IBOutlet var titleLabel: UILabel!
    @IBOutlet var releaseGenreLabel: UILabel!
    @IBOutlet var runTimeLabel: UILabel!
    @IBOutlet var addtoFavoriteButton: UIButton!
    @IBOutlet var watchLaterButton: UIButton!
    @IBOutlet var overviewReviewSegmentedControl: UISegmentedControl!
    @IBOutlet var overviewReviewTextView: UITextView!
    @IBOutlet var voteAverageLabel: UILabel!
    
    var movieId: Int!
    var interactor: DetailMovieBusinessLogic?
    var router: (NSObjectProtocol & DetailMovieRoutingLogic & DetailMovieDataPassing)?
    
    // MARK: Object lifecycle
    
    //initiate before starting lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        showDetails()
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    @IBAction func addToFavoritePressed() {
        interactor?.setFavouriteStatus()
    }
    
    @IBAction func watchLaterPressed() {
        interactor?.setWatchLaterStatus()
    }
    
    @IBAction func segmentedValueChanged(_ sender: UISegmentedControl) {
        let request = DetailMovieModels.SelectOverviewReviewsSegmentedControl.Request(selectedSegmentIndex: sender.selectedSegmentIndex)
        interactor?.selectOverviewReviewSegment(request: request)
    }
    
    // MARK: Do show details
    
    private func showDetails() {
        let request = DetailMovieModels.ShowDetails.Request(detailMovieId: movieId)
        interactor?.showDetails(request: request)
    }
    
    // MARK: Setup
    
    private func setup() { //move to configurator
        let viewController = self
        let interactor = DetailMovieInteractor()
        let presenter = DetailMoviePresenter()
        let router = DetailMovieRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}

extension DetailMovieViewController: DetailMovieDisplayLogic {
    func displayMovieDetails(viewModel: DetailMovieModels.ShowDetails.ViewModel) {
        DispatchQueue.main.async { // todo why dispatch??
            self.titleLabel.text = viewModel.displayedDetails.movieTitle
            self.releaseGenreLabel.text = viewModel.displayedDetails.releaseGenre
            self.runTimeLabel.text = viewModel.displayedDetails.runTime
            self.voteAverageLabel.text = viewModel.displayedDetails.voteAverage
            
            guard let urlTrailer = viewModel.displayedDetails.trailerUrl else { return } //add ui message trailer is missing
            self.trailerPlayer.load(URLRequest(url: urlTrailer))
            
            self.overviewReviewTextView.text = viewModel.displayedDetails.overView
            
            self.updateAddToFavoriteUISection(if: viewModel.displayedDetails.isAddedToFavourite)
            self.updateAddToWatchLaterUISection(if: viewModel.displayedDetails.isAddedToWatchLater)
            
            //            guard let reviews = viewModel.displayedDetails.reviews else { return } //add ui message reviews are missing
        }
    }
    
    func updateUIForFavouriteStatus(viewModel: DetailMovieModels.SetFavouriteStatus.ViewModel) {
        updateAddToFavoriteUISection(if: viewModel.isAddedToFavourite)
    }
    
    func updateUIForWatchLaterStatus(viewModel: DetailMovieModels.SetWatchLaterStatus.ViewModel) {
        updateAddToWatchLaterUISection(if: viewModel.isAddedToWatchLater)
    }
    
    func updateOverviewReviews(viewModel: DetailMovieModels.SelectOverviewReviewsSegmentedControl.ViewModel) {
        overviewReviewTextView.text = viewModel.overviewReviews
    }
    
    private func updateAddToFavoriteUISection(if isPresentInFavorite: Bool) {
        if !isPresentInFavorite {
            addtoFavoriteButton.setImage(UIImage(named: "heart"), for: .normal)
            addtoFavoriteButton.setTitle(" Добавить в избранное", for: .normal)
        } else {
            addtoFavoriteButton.setImage(UIImage(named: "heartColored"), for: .normal)
            addtoFavoriteButton.setTitle(" В избранном", for: .normal)
        }
    }
    
    private func updateAddToWatchLaterUISection(if isPresentInWatchLater: Bool) {
        if !isPresentInWatchLater {
            watchLaterButton.setImage(UIImage(named: "bookmark"), for: .normal)
            watchLaterButton.setTitle(" Смотреть позже", for: .normal)
        } else {
            watchLaterButton.setImage(UIImage(named: "bookmarkSelected"), for: .normal)
            watchLaterButton.setTitle(" Посмотрю позже", for: .normal)
        }
    }
}
