//
//  DetailMovieModels.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 10/13/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DetailMovieModels {
    
    // MARK: Use cases
    
    enum ShowDetails {
        
        struct Request {
            let detailMovieId: Int
        }
        
        struct Response {
            let detailMovie: DetailMovie
        }
        
        struct ViewModel {
            
            let displayedDetails: DisplayedDetails
            
            struct DisplayedDetails {
                let movieTitle: String?
                let releaseGenre: String?
                let runTime: String?
                let voteAverage: String?
            }
        }
    }
}
