//
//  DetailMovieRouter.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 10/13/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailMovieRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol DetailMovieDataPassing {
    var dataStore: DetailMovieDataStore! { get }
}

class DetailMovieRouter: NSObject, DetailMovieRoutingLogic, DetailMovieDataPassing {
    
    weak var viewController: DetailMovieViewController?
    var dataStore: DetailMovieDataStore!
    
}
