//
//  DetailMoviePresenter.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 10/13/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailMoviePresentationLogic {
    func presentDetails(response: DetailMovieModels.ShowDetails.Response)
}

class DetailMoviePresenter: DetailMoviePresentationLogic {
    
    weak var viewController: DetailMovieDisplayLogic?
    
    // MARK: Do something
    
    func presentDetails(response: DetailMovieModels.ShowDetails.Response) {
        
        let detailMovie = response.detailMovie
        
        let title = detailMovie.title
        let releaseGenre = (detailMovie.releaseDate ?? "") + ", " + (detailMovie.getGenresAsString() ?? "")
       
        var displayedRunTime: String
        if let runTime = detailMovie.runTime {
            displayedRunTime = String(runTime) + " мин"
        } else {
            displayedRunTime = ""
        }
        
        let voteAverage = "\(detailMovie.voteAverage ?? 0)"
        
        let overview = detailMovie.overview
        
        var trailerUrl: URL? = nil
        
        if let videoCode = response.videoCode {
            trailerUrl = URL(string: "https://www.youtube.com/embed/\(videoCode)")
        }
        
        var reiews: String? = nil
        if let reviewList = response.reviewList {
            reiews = reviewList.getReviewAsString()
        }
        
        let displayedDetails = DetailMovieModels.ShowDetails.ViewModel.DisplayedDetails(movieTitle: title, releaseGenre: releaseGenre, runTime: displayedRunTime, voteAverage: voteAverage, overView: overview, trailerUrl: trailerUrl, reviews: reiews)
        let viewModel = DetailMovieModels.ShowDetails.ViewModel(displayedDetails: displayedDetails)
        viewController?.displayTextDetails(viewModel: viewModel)
    }
}
