//
//  WatchLaterInteractor.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 11/4/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WatchLaterBusinessLogic {
    func getMovies(request: WatchLaterModels.GetMovies.Request)
}

protocol WatchLaterDataStore {
    var movies: [DetailMovie]! { get }
}

class WatchLaterInteractor: WatchLaterBusinessLogic, WatchLaterDataStore {
    
    var presenter: WatchLaterPresentationLogic?
    var worker: WatchLaterWorker?
    
    var movies: [DetailMovie]!
    
    // MARK: Get movies
    
    func getMovies(request: WatchLaterModels.GetMovies.Request) {
//        worker = WatchLaterWorker()
//        worker?.doSomeWork()
        
        movies = ListManager.listManager.getMovies(from: .watchLaterList)
        
        let response = WatchLaterModels.GetMovies.Response(movies: movies)
        presenter?.presentMovies(response: response)
    }
}
