//
//  WatchLaterPresenter.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 11/4/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import RealmSwift

protocol WatchLaterPresentationLogic {
    func presentMovies(response: WatchLaterModels.GetMovies.Response)
    func removeMovie(response: WatchLaterModels.RemoveMovie.Response)
}

class WatchLaterPresenter: WatchLaterPresentationLogic {
    
    weak var viewController: WatchLaterDisplayLogic?
    var worker: ListWorker?
    
    // MARK: Present movies
    
    func presentMovies(response: WatchLaterModels.GetMovies.Response) {
        worker = ListWorker()
        let movies = response.movies
        if let displayedMovieDetails = worker?.prepareDisplayedMovies(movies) {
            let viewModel = WatchLaterModels.GetMovies.ViewModel(displayedDetails: displayedMovieDetails)
            viewController?.displayMovies(viewModel: viewModel)
        }
    }
    
    //MARK: - Remove movie
    
    func removeMovie(response: WatchLaterModels.RemoveMovie.Response) {
        let movies = response.movies
        if let displayedMovieDetails = worker?.prepareDisplayedMovies(movies) {
            let viewModel = WatchLaterModels.RemoveMovie.ViewModel(displayedDetails: displayedMovieDetails)
            viewController?.removeMovie(viewModel: viewModel)
        }
    }
}
