//
//  WatchLaterViewController.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 11/4/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WatchLaterDisplayLogic: class {
    func displayMovies(viewModel: WatchLaterModels.GetMovies.ViewModel)
}

class WatchLaterViewController: UITableViewController, WatchLaterDisplayLogic {
    
    //@IBOutlet private var nameTextField: UITextField!
    
    var interactor: WatchLaterBusinessLogic?
    var router: (NSObjectProtocol & WatchLaterRoutingLogic & WatchLaterDataPassing)?
    
    private var movies: [WatchLaterModels.GetMovies.ViewModel.DisplayedDetails]!
    
    // MARK: Object lifecycle
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        WatchLaterConfigurator.shared.configure(with: self)
    }
    
    // MARK: View lifecycle
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        let request = WatchLaterModels.GetMovies.Request()
        interactor?.getMovies(request: request)
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    func displayMovies(viewModel: WatchLaterModels.GetMovies.ViewModel) {
        movies = viewModel.displayedDetails
        tableView.reloadData()
    }
    
}

// MARK: - Extension

extension WatchLaterViewController {
    
    // MARK: - Table view data source
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return movies.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath) as! MovieCell
        
        let movie = movies[indexPath.row]
        cell.configure(with: movie)
        
        return cell
    }
    
}

extension WatchLaterViewController {
    
    //MARK: - Table view delegate
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if let indexPathForSelectedRow = tableView.indexPathForSelectedRow {
            let movieId = movies[indexPathForSelectedRow.row].movieId
            let request = WatchLaterModels.SelectMovie.Request(movieId: movieId)
            interactor?.selectMovie(request: request)
            performSegue(withIdentifier: "DetailMovie", sender: nil)
        }
    }
    
}
