//
//  SearchModels.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 28.11.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum SearchModels {
   
    // MARK: Use cases
    
    enum Search {
        struct Request {
            let queryString: String
        }
        
        struct Response {
            var movies: [MovieJson]?
            let errorMessage: String?
        }
        
        struct ViewModel {
            let displayedDetails: [DisplayedDetails]?
            let errorMessage: String?
        }
    }
}
