//
//  SearchWorker.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 28.11.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

typealias searchSuccess = ([MovieJson]) -> Void
typealias searchFailure = (Error) -> Void

class SearchWorker {
   
    func searchMovies(query: String, success: @escaping searchSuccess, failure: @escaping searchFailure) {
        APIMovieManager.searchMovie(queryString: query) { (movies, result, error) in
            switch result {
            case .success:
                guard let movies = movies else { return }
                success(movies)
            case .failure:
                guard let error = error else { return }
                failure(error)
            }
        }
    }
}
