//
//  SearchInteractor.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 28.11.2019.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import RealmSwift

protocol SearchBusinessLogic {
    func searchMovie(request: SearchModels.Search.Request)
    func selectMovie(request: SearchModels.SelectMovie.Request)
}

protocol SearchDataStore {
    var movies: [MovieJson]! { get }
    var selectedMovieId: Int! { get }
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore {
    
    var presenter: SearchPresentationLogic?
    var worker: SearchWorker?
    var movies: [MovieJson]!
    var selectedMovieId: Int!
    
    // MARK: Search movie
    
    func searchMovie(request: SearchModels.Search.Request) {
        worker = SearchWorker()
        worker?.searchMovies(query: request.queryString, success: { [weak self] (movies) in
            self?.movies = movies
            let response = SearchModels.Search.Response(movies: movies, errorMessage: nil)
            self?.presenter?.presentMovies(response: response)
            }, failure: { [weak self] (error) in
                let response = SearchModels.Search.Response(movies: nil, errorMessage: error.localizedDescription)
                self?.presenter?.presentMovies(response: response)
        })
    }
    
    // MARK: Select movie
    
    func selectMovie(request: SearchModels.SelectMovie.Request) {
        selectedMovieId = request.movieId
    }
    
}
