//
//  CategoriesWorker.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 10/21/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

typealias fetchSuccess = ([MovieJson]) -> Void
typealias fetchFailure = (Error) -> Void

class CategoriesWorker {
    func fetchMovies(from movieType: MovieType, success: @escaping fetchSuccess, failure: @escaping fetchFailure) {
        APIMovieManager.fetchMovies(from: movieType) { (movies, result, error) in
            switch result {
            case .success:
                guard let movies = movies else { return }
                success(movies)
            case .failure:
                guard let error = error else { return }
                failure(error)
            }
        }
    }
}
