//
//  WelcomeModels.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 10/29/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum WelcomeModels {
   
    // MARK: Use cases
    
    //I leave these enums empty and do not remove them because I will use them further (perhaps)
    
    enum SignIn {
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum SignUp {
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum UserIsLoggedInAndExists {
        struct Request {
        }
        
        struct Response {
            var isUserLoggedInExists: Bool
        }
        
        struct ViewModel {
        }
    }
}
