//
//  WelcomeInteractor.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 10/29/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeBusinessLogic {
    func signIn()
    func signUp()
    func goToCategoriesIfUserExistsAndIsLoggedIn()
}

protocol WelcomeDataStore {
    var isSignInClicked: Bool { get }
}

class WelcomeInteractor: WelcomeBusinessLogic, WelcomeDataStore {
    
    var presenter: WelcomePresentationLogic?
    var worker: WelcomeWorker?
    
    var isSignInClicked: Bool = false
    
    // MARK: - Set data isSignInClicked
    
    func signIn() {
        isSignInClicked = true
    }
    
    func signUp() {
        isSignInClicked = false
    }
    
    //MARK: - Check if user exists and is logged in
    
    func goToCategoriesIfUserExistsAndIsLoggedIn() {
        if let user = StorageManager.shared.getUser() {
            let reponse = WelcomeModels.UserIsLoggedInAndExists.Response(isUserLoggedInExists: user.isLoggedIn)
            presenter?.presentUserExistsAndIsLoggedIn(response: reponse)
        }
    }
}
