//
//  WelcomeViewController.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 10/29/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol WelcomeDisplayLogic: class {
    func displayCategoriesIfUserExistsIsLoggedIn(viewModel: WelcomeModels.UserIsLoggedInAndExists.ViewModel)
}

class WelcomeViewController: UIViewController, WelcomeDisplayLogic {
    
    var interactor: WelcomeBusinessLogic?
    var router: (NSObjectProtocol & WelcomeRoutingLogic & WelcomeDataPassing)?
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        WelcomeConfigurator.shared.configure(with: self)
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(true)
        
        interactor?.goToCategoriesIfUserExistsAndIsLoggedIn()
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    @IBAction func unwindToWelcomeVC(_ unwindSegue: UIStoryboardSegue) {
    }
    
    @IBAction func signInUpButton(_ sender: UIButton) {
        sender.tag == 0 ? interactor?.signIn() : interactor?.signUp()
        performSegue(withIdentifier: "SignInUp", sender: self)
    }
    
    func displayCategoriesIfUserExistsIsLoggedIn(viewModel: WelcomeModels.UserIsLoggedInAndExists.ViewModel) {
        performSegue(withIdentifier: "ShowCategories", sender: nil)
    }
    
}
