//
//  ProfilePresenter.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 11/2/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilePresentationLogic {
    func presentLoggedOut(response: Profile.Something.Response)
}

class ProfilePresenter: ProfilePresentationLogic {
    
    weak var viewController: ProfileDisplayLogic?
    
    // MARK: Do something
    
    func presentLoggedOut(response: Profile.Something.Response) {
        let viewModel = Profile.Something.ViewModel()
        viewController?.displayLoggedOut(viewModel: viewModel)
    }
}
