//
//  ProfileInteractor.swift
//  MovieInfoUrlSession
//
//  Created by Игорь on 11/2/19.
//  Copyright (c) 2019 Igor Zhyzhyrii. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileBusinessLogic {
    func logOut()
}

protocol ProfileDataStore {
    var user: User! { get }
}

class ProfileInteractor: ProfileBusinessLogic, ProfileDataStore {
    
    
    var presenter: ProfilePresentationLogic?
    var worker: ProfileWorker?
    
    var user: User!
    
    // MARK: Do something
    
    func logOut() {
//        worker = ProfileWorker()
//        worker?.doSomeWork()
        guard var user = StorageManager.shared.getUser() else { return }
        user.isLoggedIn = false
        StorageManager.shared.saveUser(user)
        let response = Profile.Something.Response()
        presenter?.presentLoggedOut(response: response)
    }
}
